/*
 * This file is generated by jOOQ.
 */
package com.jyonkudo.bookmanager.jooq.genarated.tables.records;


import com.jyonkudo.bookmanager.jooq.genarated.tables.Author;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 著者テーブル
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthorRecord extends UpdatableRecordImpl<AuthorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>book_manager.author.id</code>. 著者ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>book_manager.author.id</code>. 著者ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>book_manager.author.name</code>. 著者名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>book_manager.author.name</code>. 著者名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>book_manager.author.birth_date</code>. 生年月日
     */
    public void setBirthDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>book_manager.author.birth_date</code>. 生年月日
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorRecord
     */
    public AuthorRecord() {
        super(Author.AUTHOR);
    }

    /**
     * Create a detached, initialised AuthorRecord
     */
    public AuthorRecord(Integer id, String name, LocalDate birthDate) {
        super(Author.AUTHOR);

        setId(id);
        setName(name);
        setBirthDate(birthDate);
        resetChangedOnNotNull();
    }
}
