/*
 * This file is generated by jOOQ.
 */
package com.jyonkudo.bookmanager.jooq.genarated.tables.records;


import com.jyonkudo.bookmanager.jooq.genarated.enums.BookPublicationStatus;
import com.jyonkudo.bookmanager.jooq.genarated.tables.Book;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 書籍テーブル
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>book_manager.book.id</code>. 書籍ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>book_manager.book.id</code>. 書籍ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>book_manager.book.title</code>. タイトル
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>book_manager.book.title</code>. タイトル
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>book_manager.book.price</code>. 価格
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>book_manager.book.price</code>. 価格
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>book_manager.book.publication_status</code>. 出版状況
     */
    public void setPublicationStatus(BookPublicationStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>book_manager.book.publication_status</code>. 出版状況
     */
    public BookPublicationStatus getPublicationStatus() {
        return (BookPublicationStatus) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, String title, Integer price, BookPublicationStatus publicationStatus) {
        super(Book.BOOK);

        setId(id);
        setTitle(title);
        setPrice(price);
        setPublicationStatus(publicationStatus);
        resetChangedOnNotNull();
    }
}
