/*
 * This file is generated by jOOQ.
 */
package com.jyonkudo.bookmanager.jooq.genarated.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * 出版状況
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum BookPublicationStatus implements EnumType {

    NOT_PUBLISHED("NOT_PUBLISHED"),

    PUBLISHED("PUBLISHED");

    private final String literal;

    private BookPublicationStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static BookPublicationStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(BookPublicationStatus.class, literal);
    }
}
