/*
 * This file is generated by jOOQ.
 */
package com.jyonkudo.bookmanager.jooq.genarated;


import com.jyonkudo.bookmanager.jooq.genarated.tables.Author;
import com.jyonkudo.bookmanager.jooq.genarated.tables.Book;
import com.jyonkudo.bookmanager.jooq.genarated.tables.BookAuthor;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookManager extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>book_manager</code>
     */
    public static final BookManager BOOK_MANAGER = new BookManager();

    /**
     * 著者テーブル
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * 書籍テーブル
     */
    public final Book BOOK = Book.BOOK;

    /**
     * 書籍・著者関連テーブル
     */
    public final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * No further instances allowed
     */
    private BookManager() {
        super("book_manager", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR,
            Book.BOOK,
            BookAuthor.BOOK_AUTHOR
        );
    }
}
