/*
 * This file is generated by jOOQ.
 */
package com.jyonkudo.bookmanager.jooq.genarated;


import com.jyonkudo.bookmanager.jooq.genarated.tables.Author;
import com.jyonkudo.bookmanager.jooq.genarated.tables.Book;
import com.jyonkudo.bookmanager.jooq.genarated.tables.BookAuthor;


/**
 * Convenience access to all tables in book_manager.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 著者テーブル
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * 書籍テーブル
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * 書籍・著者関連テーブル
     */
    public static final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;
}
